on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el entorno'
        required: true
        type: choice
        options: [development, qa, demo, uat, prod]

permissions:
    id-token: write
    contents: read
    issues: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Authenticate with Firebase using service account
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-key.json
        run: |
          echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}' > /tmp/firebase-key.json
      
      - name: Deploy to Firebase
        run: |
          firebase deploy --project tutu-back-2 --token "$(firebase auth:print-access-token)"


      

      
