on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el entorno'
        required: true
        type: choice
        options: [development, qa, demo, uat, prod]

permissions:
    id-token: write
    contents: read
    issues: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: "Install gcloud cli"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
          
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
      
      - name: Run flutterfire configure
        run: |
          dart pub global activate flutterfire_cli
          firebase projects:list --json 


      

      
